name: images_mirror

# 当新建或者修改 issues 时，触发当前 workflow
on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Show Machine Info
      run: |
        df -hT
        lscpu
        cat /proc/cpuinfo
        echo "--------------------------"
        cat /proc/meminfo
        echo "--------------------------"
    # -name: download
    #   run: |
    #     docker pull 