name: images_mirror

# 当新建或者修改 issues 时，触发当前 workflow
on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Issue Title
      if: ${{ !contains(github.event.issue.title, 'DOCKER') }}
      run: |
        # 反写 Issue
        # 暂时取消 --240705
        # echo "Updating Issue description"
        # curl \
        #   -X PATCH \
        #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        #   -H "Accept: application/vnd.github.v3+json" \
        #   https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
        #   -d '{"body": "Title of issue does not contain the 'DOCKER'"}'
        exit 1
    - name: Checkout
      uses: actions/checkout@main
    - name: Show Machine Info
      run: |
        df -hT
        lscpu
        cat /proc/cpuinfo
        echo "--------------------------"
        cat /proc/meminfo
        echo "--------------------------"
    # -name: download
    #   run: |
    #     docker pull 