name: Process Issue Content

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch issue content
      id: fetch_issue
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.issue.number;
          const issue = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number
          });
          const issue_body = issue.data.body;
          core.setOutput('issue_body', issue_body);
          core.setOutput('issue_number', issue_number);

    - name: Process issue content
      run: |
        echo "Issue Content: ${{ steps.fetch_issue.outputs.issue_body }}"
        echo "${{ steps.fetch_issue.outputs.issue_body }}" > issue.json

    - name: Parse and loop through array
      run: |
        issue_content=$(cat issue.json)
        echo "Issue Content: $issue_content"
        hub_mirror=$(echo "$issue_content" | jq -r '.["hub-mirror"][]')

        for item in $hub_mirror; do
          echo "Processing item: $item"
          # 在这里添加你要对每个 item 进行的操作
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Close issue
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = "${{ steps.fetch_issue.outputs.issue_number }}";
          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(issue_number, 10),
            state: 'closed'
          });